In [1]:
import pandas as pd

# Load the data
listings_data = pd.read_csv('./dataSource/raw/listings.csv')
calendar_data = pd.read_csv('./dataSource/raw/calendar.csv')

# Show the first few rows of the data
listings_head = listings_data.head()
calendar_head = calendar_data.head()

listings_head, calendar_head

(       id                          listing_url       scrape_id last_scraped  \
 0   71609   https://www.airbnb.com/rooms/71609  20230923135002   2023-09-23
 1   71896   https://www.airbnb.com/rooms/71896  20230923135002   2023-09-23
 2   71903   https://www.airbnb.com/rooms/71903  20230923135002   2023-09-23
 3  275343  https://www.airbnb.com/rooms/275343  20230923135002   2023-09-23
 4  275344  https://www.airbnb.com/rooms/275344  20230923135002   2023-09-23

             source                                               name  \
 0  previous scrape  Villa in Singapore · ★4.44 · 2 bedrooms · 3 be...
 1  previous scrape  Home in Singapore · ★4.16 · 1 bedroom · 1 bed ...
 2  previous scrape  Home in Singapore · ★4.41 · 1 bedroom · 2 beds...
 3      city scrape  Rental unit in Singapore · ★4.40 · 1 bedroom ·...
 4      city scrape  Rental unit in Singapore · ★4.27 · 1 bedroom ·...

                                          description  \
 0  For 3 rooms.Book room 1&2 and room 4<br /><br ...
 1  <b>The space</b><br />Vocational Stay Deluxe B...
 2  Like your own home, 24hrs access.<br /><br /><...
 3  **IMPORTANT NOTES:  READ BEFORE YOU BOOK! <br ...
 4  Lovely home for the special guest !<br /><br /...

                                neighborhood_overview  \
 0                                                NaN
 1                                                NaN
 2  Quiet and view of the playground with exercise...
 3                                                NaN
 4       Bus stop <br />Food center <br />Supermarket

                                          picture_url  host_id  ...  \
 0  https://a0.muscache.com/pictures/24453191/3580...   367042  ...
 1  https://a0.muscache.com/pictures/2440674/ac4f4...   367042  ...
 2  https://a0.muscache.com/pictures/568743/7bc623...   367042  ...
 3  https://a0.muscache.com/pictures/miso/Hosting-...  1439258  ...
 4  https://a0.muscache.com/pictures/miso/Hosting-...  1439258  ...

   review_scores_communication review_scores_location review_scores_value  \
 0                        4.78                   4.26                4.32
 1                        4.43                   4.17                4.04
 2                        4.64                   4.50                4.36
 3                        4.42                   4.53                4.63
 4                        4.50                   4.63                4.13

   license instant_bookable calculated_host_listings_count  \
 0     NaN                f                              5
 1     NaN                f                              5
 2     NaN                f                              5
 3   S0399                t                             52
 4   S0399                t                             52

   calculated_host_listings_count_entire_homes  \
 0                                           0
 1                                           0
 2                                           0
 3                                           1
 4                                           1

   calculated_host_listings_count_private_rooms  \
 0                                            5
 1                                            5
 2                                            5
 3                                           51
 4                                           51

   calculated_host_listings_count_shared_rooms reviews_per_month
 0                                           0              0.14
 1                                           0              0.16
 2                                           0              0.31
 3                                           0              0.17
 4                                           0              0.12

 [5 rows x 75 columns],
    listing_id        date available    price adjusted_price  minimum_nights  \
 0       71609  2023-09-23         f  $150.00        $150.00              92
 1       71609  2023-09-24         f  $150.00        $150.00              92
 2       71609  2023-09-25         t  $150.00        $150.00              92
 3       71609  2023-09-26         t  $150.00        $150.00              92
 4       71609  2023-09-27         t  $150.00        $150.00              92

    maximum_nights
 0            1125
 1            1125
 2            1125
 3            1125
 4            1125  )

In [2]:
import numpy as np

# Step 1: Data Preprocessing and Cleaning

# 1.1 Convert 'price' from string to float in calendar data
calendar_data['price'] = calendar_data['price'].replace('[\$,]', '', regex=True).astype(float)
calendar_data['adjusted_price'] = calendar_data['adjusted_price'].replace('[\$,]', '', regex=True).astype(float)

# 1.2 Convert 'date' from string to datetime in calendar data
calendar_data['date'] = pd.to_datetime(calendar_data['date'])

# 1.3 Check for missing values
missing_values_listings = listings_data.isnull().sum()
missing_values_calendar = calendar_data.isnull().sum()

missing_values_listings, missing_values_calendar

(id                                                 0
 listing_url                                        0
 scrape_id                                          0
 last_scraped                                       0
 source                                             0
                                                 ...
 calculated_host_listings_count                     0
 calculated_host_listings_count_entire_homes        0
 calculated_host_listings_count_private_rooms       0
 calculated_host_listings_count_shared_rooms        0
 reviews_per_month                               1565
 Length: 75, dtype: int64,
 listing_id        0
 date              0
 available         0
 price             0
 adjusted_price    0
 minimum_nights    0
 maximum_nights    0
 dtype: int64)

In [3]:
# Handling missing values

# Listings Data: Fill missing values in 'reviews_per_month' with 0
listings_data['reviews_per_month'] = listings_data['reviews_per_month'].fillna(0)

# Calendar Data: Drop rows with missing values
calendar_data = calendar_data.dropna()

# Check again to confirm missing values are handled
missing_values_listings = listings_data.isnull().sum()
missing_values_calendar = calendar_data.isnull().sum()

missing_values_listings, missing_values_calendar

(id                                              0
 listing_url                                     0
 scrape_id                                       0
 last_scraped                                    0
 source                                          0
                                                ..
 calculated_host_listings_count                  0
 calculated_host_listings_count_entire_homes     0
 calculated_host_listings_count_private_rooms    0
 calculated_host_listings_count_shared_rooms     0
 reviews_per_month                               0
 Length: 75, dtype: int64,
 listing_id        0
 date              0
 available         0
 price             0
 adjusted_price    0
 minimum_nights    0
 maximum_nights    0
 dtype: int64)

In [4]:
# Selecting relevant features from listings data
selected_features = [
    'id', 'room_type', 'accommodates', 'bedrooms', 'beds', 'bathrooms_text',
    'amenities', 'price', 'minimum_nights', 'maximum_nights', 'availability_30',
    'availability_60', 'availability_90', 'availability_365', 'number_of_reviews',
    'reviews_per_month', 'review_scores_rating'
]
listings_selected = listings_data[selected_features]

# Converting 'price' from string to float in listings data
listings_selected['price'] = listings_selected['price'].replace('[\$,]', '', regex=True).astype(float)

# Merging the data on listing ID
merged_data = pd.merge(calendar_data, listings_selected, left_on='listing_id', right_on='id', how='left')

# Showing the first few rows of the merged data
merged_data.head()

/tmp/ipykernel_2802/113879376.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_selected['price'] = listings_selected['price'].replace('[\$,]', '', regex=True).astype(float)

,listing_id,date,available,price_x,adjusted_price,minimum_nights_x,maximum_nights_x,id,room_type,accommodates,...,price_y,minimum_nights_y,maximum_nights_y,availability_30,availability_60,availability_90,availability_365,number_of_reviews,reviews_per_month,review_scores_rating
0,71609,2023-09-23,f,150.0,150.0,92,1125,71609,Private room,3,...,150.0,92,365,28,58,88,89,20,0.14,4.44
1,71609,2023-09-24,f,150.0,150.0,92,1125,71609,Private room,3,...,150.0,92,365,28,58,88,89,20,0.14,4.44
2,71609,2023-09-25,t,150.0,150.0,92,1125,71609,Private room,3,...,150.0,92,365,28,58,88,89,20,0.14,4.44
3,71609,2023-09-26,t,150.0,150.0,92,1125,71609,Private room,3,...,150.0,92,365,28,58,88,89,20,0.14,4.44
4,71609,2023-09-27,t,150.0,150.0,92,1125,71609,Private room,3,...,150.0,92,365,28,58,88,89,20,0.14,4.44

In [5]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Adding date features
merged_data['year'] = merged_data['date'].dt.year
merged_data['month'] = merged_data['date'].dt.month
merged_data['day'] = merged_data['date'].dt.day
merged_data['dayofweek'] = merged_data['date'].dt.dayofweek

# Handling text features
# For simplicity, we will fill missing values in 'bathrooms_text' with the most common value and extract the number of bathrooms
merged_data['bathrooms_text'] = merged_data['bathrooms_text'].fillna(merged_data['bathrooms_text'].mode()[0])
merged_data['bathrooms'] = merged_data['bathrooms_text'].str.extract('(\d+\.?\d?)').astype(float)

# Handling categorical features
label_encoder = LabelEncoder()
merged_data['room_type'] = label_encoder.fit_transform(merged_data['room_type'])

# Showing the first few rows of the updated data
merged_data.head()

,listing_id,date,available,price_x,adjusted_price,minimum_nights_x,maximum_nights_x,id,room_type,accommodates,...,availability_90,availability_365,number_of_reviews,reviews_per_month,review_scores_rating,year,month,day,dayofweek,bathrooms
0,71609,2023-09-23,f,150.0,150.0,92,1125,71609,2,3,...,88,89,20,0.14,4.44,2023,9,23,5,1.0
1,71609,2023-09-24,f,150.0,150.0,92,1125,71609,2,3,...,88,89,20,0.14,4.44,2023,9,24,6,1.0
2,71609,2023-09-25,t,150.0,150.0,92,1125,71609,2,3,...,88,89,20,0.14,4.44,2023,9,25,0,1.0
3,71609,2023-09-26,t,150.0,150.0,92,1125,71609,2,3,...,88,89,20,0.14,4.44,2023,9,26,1,1.0
4,71609,2023-09-27,t,150.0,150.0,92,1125,71609,2,3,...,88,89,20,0.14,4.44,2023,9,27,2,1.0

In [6]:
from sklearn.model_selection import train_test_split

# Sorting the data based on date
merged_data = merged_data.sort_values(by='date')

# Selecting features and target variable
X = merged_data.drop(columns=['listing_id', 'date', 'available', 'price_x', 'adjusted_price', 'id', 'bathrooms_text', 'amenities'])
y = merged_data['price_x']

# Splitting the data into training and testing sets
# We will use the last 30 days data as testing set
train_size = int(len(merged_data) * 0.9)
X_train, X_test = X.iloc[:train_size], X.iloc[train_size:]
y_train, y_test = y.iloc[:train_size], y.iloc[train_size:]

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1144146, 21), (127128, 21), (1144146,), (127128,))

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

# Handling infinite and NaN values (if any)
X_train = np.nan_to_num(X_train)
y_train = np.nan_to_num(y_train)
X_test = np.nan_to_num(X_test)
y_test = np.nan_to_num(y_test)

# Baseline Model: Linear Regression
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)
y_pred_baseline = linear_reg.predict(X_test)

# Evaluating the Baseline Model
mse_baseline = mean_squared_error(y_test, y_pred_baseline)
rmse_baseline = np.sqrt(mse_baseline)
rmse_baseline

696.2335464100299

In [8]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)

In [9]:
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [10]:
feature_importances = rf.feature_importances_

In [11]:
feature_importances

array([1.03598963e-03, 1.04624283e-03, 3.64447266e-04, 6.24253907e-04,
       9.79248011e-05, 9.20083509e-05, 3.90013816e-01, 1.84917609e-04,
       8.16491790e-03, 1.70441820e-04, 1.91707577e-04, 1.65791199e-04,
       3.93192583e-04, 2.54126690e-03, 2.08444739e-03, 2.26195925e-03,
       3.61366385e-01, 2.18237193e-01, 7.04026353e-03, 3.86524586e-03,
       5.75871368e-05])

In [8]:
feature_importances=np.array([1.03598963e-03, 1.04624283e-03, 3.64447266e-04, 6.24253907e-04,
       9.79248011e-05, 9.20083509e-05, 3.90013816e-01, 1.84917609e-04,
       8.16491790e-03, 1.70441820e-04, 1.91707577e-04, 1.65791199e-04,
       3.93192583e-04, 2.54126690e-03, 2.08444739e-03, 2.26195925e-03,
       3.61366385e-01, 2.18237193e-01, 7.04026353e-03, 3.86524586e-03,
       5.75871368e-05])

In [9]:
import numpy as np

# 设置选择特征的阈值或者选择前N个特征
threshold = 0.01  # 例如，选择重要性大于0.01的特征
selected_features = np.where(feature_importances > threshold)[0]

# 创建新的特征子集
X_train_selected = X_train[:, selected_features]
X_test_selected = X_test[:, selected_features]

# 训练新模型（以线性回归为例）
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train_selected, y_train)
y_pred = model.predict(X_test_selected)

# 计算RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('RMSE:', rmse)

RMSE: 708.8579087390651

In [9]:
import numpy as np

# 设置选择特征的阈值或者选择前N个特征
threshold = 0.05  # 例如，选择重要性大于0.01的特征
selected_features = np.where(feature_importances > threshold)[0]

# 创建新的特征子集
X_train_selected = X_train[:, selected_features]
X_test_selected = X_test[:, selected_features]

# 训练新模型（以线性回归为例）
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train_selected, y_train)
y_pred = model.predict(X_test_selected)

# 计算RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('RMSE:', rmse)

RMSE: 708.8579087390651

In [9]:


# 选择前N个最重要的特征
N = 10  # 例如，选择前10个最重要的特征
selected_features = np.argsort(feature_importances)[-N:]

# 创建新的特征子集
X_train_selected = X_train[:, selected_features]
X_test_selected = X_test[:, selected_features]

In [10]:
model = LinearRegression()
model.fit(X_train_selected, y_train)
y_pred = model.predict(X_test_selected)

In [11]:
# 训练新模型（以线性回归为例）




# 计算RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('RMSE:', rmse)

RMSE: 707.104259935596