In [7]:
import pandas as pd

processed_data = pd.read_csv('./processed_data_merged.csv')
merged_data=pd.read_csv('./data_merged(final+version).csv')

# def replace_value(row):
#     if 'Singapore' in row['name']:
#         return row['name'].replace('Singapore', row['neighbourhood_cleansed'])
#     else:
#         return row['name']
    

# merged_data['name'] = merged_data['name'].str.split('Singapore').str[0]
column1_to_add = merged_data['name'].str.split(' · ',n=2).str[2]

merged_data['name'] = merged_data['name'].str.split(' in ').str[0]
merged_data['name']= merged_data['name']+' in '+merged_data['neighbourhood_cleansed']

column2_to_add=merged_data['name']
column3_to_add=merged_data['accommodates']
column4_to_add=merged_data['picture_url']

processed_data.insert(1, 'details', column1_to_add)
processed_data.insert(1, 'name', column2_to_add)
processed_data.insert(16, 'accommodates', column3_to_add)
processed_data.insert(5, 'picture_url', column4_to_add)

processed_data.to_csv('processed_data_merged_final_v1.csv', index=False)

new=pd.read_csv('./processed_data_merged_final_v1.csv')
new.head()

,id,name,details,neighbourhood_cleansed,neighbourhood_group_cleansed,picture_url,latitude,longitude,room_type,price,...,Wifi,kitchen,Backyard,TV,refrigerator,Microwave,Oven,Pets,stove,fan
0,71609,Villa in Tampines,2 bedrooms · 3 beds · 1 private bath,Tampines,East Region,https://a0.muscache.com/pictures/24453191/3580...,1.34537,103.95887,Private room,4170,...,1,1,1,1,1,0,0,0,0,0
1,71896,Home in Tampines,1 bedroom · 1 bed · Shared half-bath,Tampines,East Region,https://a0.muscache.com/pictures/2440674/ac4f4...,1.34754,103.95958,Private room,2100,...,1,1,1,1,1,0,0,0,0,0
2,71903,Home in Tampines,1 bedroom · 2 beds · Shared half-bath,Tampines,East Region,https://a0.muscache.com/pictures/568743/7bc623...,1.34531,103.96100,Private room,2430,...,1,1,0,1,0,0,0,0,0,0
3,275343,Rental unit in Bukit Merah,1 bedroom · 1 bed · 2 shared baths,Bukit Merah,Central Region,https://a0.muscache.com/pictures/miso/Hosting-...,1.29015,103.80814,Private room,1650,...,1,1,0,1,1,0,0,0,1,0
4,275344,Rental unit in Bukit Merah,1 bedroom · 1 bed · 2.5 shared baths,Bukit Merah,Central Region,https://a0.muscache.com/pictures/miso/Hosting-...,1.28836,103.81144,Private room,2070,...,1,1,0,1,1,1,0,0,1,0

In [8]:
# delete row with empty values

import pandas as pd


df = pd.read_csv('processed_data_merged_final_v1.csv')

print("Shape before delete:", df.shape)
df_cleaned = df.dropna()
print("Shape after delete:", df_cleaned.shape)
df_cleaned.to_csv('processed_data_merged_final_v2.csv', index=False)

df_cleaned.head()

Shape before delete: (3443, 34)
Shape after delete: (3441, 34)

,id,name,details,neighbourhood_cleansed,neighbourhood_group_cleansed,picture_url,latitude,longitude,room_type,price,...,Wifi,kitchen,Backyard,TV,refrigerator,Microwave,Oven,Pets,stove,fan
0,71609,Villa in Tampines,2 bedrooms · 3 beds · 1 private bath,Tampines,East Region,https://a0.muscache.com/pictures/24453191/3580...,1.34537,103.95887,Private room,4170,...,1,1,1,1,1,0,0,0,0,0
1,71896,Home in Tampines,1 bedroom · 1 bed · Shared half-bath,Tampines,East Region,https://a0.muscache.com/pictures/2440674/ac4f4...,1.34754,103.95958,Private room,2100,...,1,1,1,1,1,0,0,0,0,0
2,71903,Home in Tampines,1 bedroom · 2 beds · Shared half-bath,Tampines,East Region,https://a0.muscache.com/pictures/568743/7bc623...,1.34531,103.96100,Private room,2430,...,1,1,0,1,0,0,0,0,0,0
3,275343,Rental unit in Bukit Merah,1 bedroom · 1 bed · 2 shared baths,Bukit Merah,Central Region,https://a0.muscache.com/pictures/miso/Hosting-...,1.29015,103.80814,Private room,1650,...,1,1,0,1,1,0,0,0,1,0
4,275344,Rental unit in Bukit Merah,1 bedroom · 1 bed · 2.5 shared baths,Bukit Merah,Central Region,https://a0.muscache.com/pictures/miso/Hosting-...,1.28836,103.81144,Private room,2070,...,1,1,0,1,1,1,0,0,1,0

In [3]:
import pandas as pd
import re

original = pd.read_csv('processed_data_merged_final_v2.csv')

type_to_add=original['name']
type_to_add = type_to_add.str.split(' in ').str[0]

studio_to_add=original['details']
studio_to_add = studio_to_add.apply(lambda x: 1 if 'Studio' in x else 0)

shared_bath_to_add=original['details']
shared_bath_to_add=shared_bath_to_add.apply(lambda x: 0.5 if 'Shared half-bath' in x else 0)

private_bath_to_add=original['details']
private_bath_to_add=private_bath_to_add.apply(lambda x: 0.5 if 'Private half-bath' in x else 0)

def parse_room_info(info):
    counts = {}  


    matches = re.findall(r'(\d+(\.\d+)?)\s*([\w\s]+)\b', info)
    for count, _, room_type in matches:
        counts[room_type.strip()] = float(count)

    return counts

parsed_room_info = original['details'].apply(parse_room_info)

parsed_df = pd.DataFrame(parsed_room_info.tolist(), index=original.index)


df = pd.concat([original, parsed_df], axis=1)
df.insert(1, 'types', type_to_add)

df[['bedrooms', 'bedroom', 'beds', 'bed', 'shared baths','private bath', 'shared bath', 'baths', 'bath']] = df[['bedrooms', 'bedroom', 'beds', 'bed', 'shared baths','private bath', 'shared bath', 'baths', 'bath']].fillna(0)
df['total_bedrooms'] = df['bedrooms'] + df['bedroom']
df['total_beds'] = df['beds'] + df['bed']
df['total_shared_baths'] = df['shared baths'] + df['shared bath']+shared_bath_to_add

df['private bath']=df['private bath']+ private_bath_to_add
df['total_baths'] = df['baths'] + df['bath']

def get_bath_type(row):
    if row['private bath'] != 0:
        return 'private'
    elif row['total_shared_baths'] != 0:
        return 'shared'
    elif row['total_baths'] != 0:
        return 'unknown'
    else:
        return 'none'

df['bath_type'] = df.apply(get_bath_type, axis=1)

df['total_baths'] =df['total_baths'] +df['total_shared_baths']+ df['private bath']


df = df.drop(columns=['bedrooms', 'bedroom', 'beds', 'bed', 'shared baths', 'shared bath', 'baths', 'bath','total_shared_baths','private bath'])
df.insert(loc=len(df.columns), column='studio', value=studio_to_add)

df.to_csv('data_merged_5002_v2.csv', index=False)

df.head()

,id,types,name,details,neighbourhood_cleansed,neighbourhood_group_cleansed,picture_url,latitude,longitude,room_type,...,Microwave,Oven,Pets,stove,fan,total_bedrooms,total_beds,total_baths,bath_type,studio
0,71609,Villa,Villa in Tampines,2 bedrooms · 3 beds · 1 private bath,Tampines,East Region,https://a0.muscache.com/pictures/24453191/3580...,1.34537,103.95887,Private room,...,0,0,0,0,0,2.0,3.0,1.0,private,0
1,71896,Home,Home in Tampines,1 bedroom · 1 bed · Shared half-bath,Tampines,East Region,https://a0.muscache.com/pictures/2440674/ac4f4...,1.34754,103.95958,Private room,...,0,0,0,0,0,1.0,1.0,0.5,shared,0
2,71903,Home,Home in Tampines,1 bedroom · 2 beds · Shared half-bath,Tampines,East Region,https://a0.muscache.com/pictures/568743/7bc623...,1.34531,103.96100,Private room,...,0,0,0,0,0,1.0,2.0,0.5,shared,0
3,275343,Rental unit,Rental unit in Bukit Merah,1 bedroom · 1 bed · 2 shared baths,Bukit Merah,Central Region,https://a0.muscache.com/pictures/miso/Hosting-...,1.29015,103.80814,Private room,...,0,0,0,1,0,1.0,1.0,2.0,shared,0
4,275344,Rental unit,Rental unit in Bukit Merah,1 bedroom · 1 bed · 2.5 shared baths,Bukit Merah,Central Region,https://a0.muscache.com/pictures/miso/Hosting-...,1.28836,103.81144,Private room,...,1,0,0,1,0,1.0,1.0,2.5,shared,0

In [1]:
import folium
import time 

# 输入经纬度坐标
start_time = time.time()
latitude = 37.7749
longitude = -122.4194

# 创建地图对象
m = folium.Map(location=[latitude, longitude], zoom_start=15)

# 添加标注
folium.Marker([latitude, longitude], tooltip='Your Location').add_to(m)

# 保存地图为 HTML 文件
m.save('map_with_marker.html')
end_time = time.time()
elapsed_time = end_time - start_time
print(f"process time：{elapsed_time:.4f} seconds")

process time：0.0023 seconds